version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
  pre_build:
    commands:
      - echo Pre-build phase started
  build:
    commands:
      - echo Build started on `date`
      - echo Zipping application
      - zip -r app.zip app/ appspec.yml scripts/
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - app.zip
